name: env_cdec_maps

channels:
  - pyviz
  - conda-forge
  - defaults
 
dependencies:
  #basics
  - python=3.8
  - pip
  - ipykernel
  - autopep8
  #for tests
  - pytest
  #data
  - pandas
  - dask
  - numba
  - aiohttp
  - requests
  # decorator support for caching
  - decorator
  # support for html parsing
  - lxml
  - html5lib
  - bs4
  #visualization
  - geopandas
  - holoviews 
  - hvplot
  - matplotlib
  - bokeh
  - geoviews
  - spatialpandas
  #cache
  - requests-cache

# pip install cdec-maps here 
# pip install -e . --no-deps