name: cdec_maps
channels:
  - cadwr-dms
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - ipykernel
  - pyarrow
  - pandas
  - dask
  - numba
  - aiohttp
  - requests
  - decorator
  - lxml
  - html5lib
  - bs4
  - cartopy
  #- geopandas
  #- holoviews
  #- hvplot
  - matplotlib
  #- bokeh
  #- geoviews
  #- spatialpandas
  - diskcache
  - tqdm
  - vtools3
  - pydsm
  - pydelmod
  - pip: #FIXME: temporary till 1.5.0 is released
    - holoviews
    - hvplot
    - geopandas
    - geoviews
    - spatialpandas
    - panel==1.5.0b3
# pip install cdec-maps here
# pip install -e . --no-deps