name: cdec_maps
channels:
  - cadwr-dms
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - ipykernel
  - pyarrow
  - pandas
  - dask
  - numba
  - aiohttp
  - requests
  - decorator
  - lxml
  - html5lib
  - bs4
  - cartopy
  - geopandas
  - holoviews
  - hvplot
  - matplotlib
  - bokeh
  - geoviews
  - spatialpandas
  - panel
  - diskcache
  - tqdm
  - vtools3
  - pydsm
  - pydelmod
# pip install cdec-maps here 
# pip install -e . --no-deps