name: cdec_maps
channels:
  - cadwr-dms
  - conda-forge
dependencies:
  - python
  - pip
  - ipykernel
  - pyarrow
  - pandas
  - dask
  - numba
  - aiohttp
  - requests
  - decorator
  - lxml
  - html5lib
  - bs4
  - cartopy
  - geopandas
  - holoviews=1.20.0 # temporary pinning for issue #6516
  - hvplot
  - matplotlib
  - bokeh
  - geoviews
  - spatialpandas
  - panel
  - diskcache
  - tqdm
  - vtools3
  - pydsm
  - pydelmod
#  pip install -e . --no-deps